### ISSUE TITLE
DAL and Services/Repository appear to be misnamed

### ISSUE THREAD

**Issue by WtheFourth** [newtonrd/InventoryManagement-BT#9]
[InventoryManagementRepository](https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/Services/InventoryManagementRepository.cs) appears to be actual data access, while your [data access layer](https://github.com/newtonrd/InventoryManagement-BT/blob/master/InventoryManagement-BT/DAL/InventoryManagementContext.cs) appears to be defining the data more than accessing it.

**Comment by mjknowles** [comment]
Yeah I would stick InventoryManagementRepository inside your DAL folder. Looks like there isn't a service layer because the application is simple, but be ready to explain that and what a service layer would be used for in a more complex system (think CTS service layer not RS service layer - basically classes where you can include your non-domain specific business logic).

I also recommend breaking up the repository class into multiple repositories objects, i.e. AssetRepository, ProductRepository, LocationRepository, etc.
